# Configuration de la connexion à la base de données.
spring:
  datasource:
    url: jdbc:h2:mem:banque
    username: root
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true # Pour eviter que le script data.sql s'execute avant l'initialisation Hibernate.
  h2:
    console.enabled: true # Accès à la console H2 dans votre navigateur http://localhost:8080/h2-console
  jackson:
    spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
    spring.jackson.time-zone=Europe/Paris
